export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"
export const LOAD_USER = "LOAD_USER"

export const LOAD_PROFILE_SUCCESS = "LOAD_PROFILE_SUCCESS"
export const LOAD_PROFILE_FAIL = "LOAD_PROFILE_FAIL"

export const POST_PROFILE_SUCCESS = "POST_PROFILE_SUCCESS"
export const POST_PROFILE_FAIL = "POST_PROFILE_FAIL"

export const LOAD_POST_SUCCESS = "LOAD_POST_SUCCESS"
export const LOAD_POST_FAIL = "LOAD_POST_FAIL"

export const COMMENT_POST_SUCCESS = "COMMENT_POST_SUCCESS" 
export const COMMENT_POST_FAIL = "COMMENT_POST_FAIL" 

export const REMOVE_COMMENT_SUCCESS = "REMOVE_COMMENT_SUCCESS"
export const REMOVE_COMMENT_FAIL = "REMOVE_COMMENT_FAIL"
export const SET_LOADING = "SET_LOADING"

export const CLEAR_PROFILE = "CLEAR_PROFILE" 

export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS"
export const GET_POSTS_FAIL = "GET_POSTS_FAIL"

export const POST_POST_SUCCESS = "POST_POST_SUCCESS"
export const POST_POST_FAIL = "POST_POST_SUCCESS"

export const GET_POST_SUCCESS =  "GET_POST_SUCCESS"
export const GET_POST_FAIL =  "GET_POST_FAIL"

export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS" 
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL" 